<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: arith.proto

namespace GPBMetadata;

class Arith
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab2010a0b61726974682e70726f746f120570726f746f22240a0c41726974685265717565737412090a016118012001280512090a0162180220012805221c0a0d4172697468526573706f6e7365120b0a0370726f18012001280532450a0c41726974685365727669636512350a086d756c7469706c7912132e70726f746f2e4172697468526571756573741a142e70726f746f2e4172697468526573706f6e736542095a072e3b70726f746f620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

