// Code generated by protoc-gen-bm v0.1, DO NOT EDIT.
// source: hello.proto

package proto

import (
	"context"

	bm "github.com/go-kratos/kratos/pkg/net/http/blademaster"
	"github.com/go-kratos/kratos/pkg/net/http/blademaster/binding"
)

// to suppressed 'imported but not used warning'
var _ *bm.Context
var _ context.Context
var _ binding.StructValidator

var PathHelloServiceSayHello = "/proto.HelloService/SayHello"

// HelloServiceBMServer is the server API for HelloService service.
type HelloServiceBMServer interface {
	SayHello(ctx context.Context, req *HelloRequest) (resp *HelloResponse, err error)
}

var HelloServiceSvc HelloServiceBMServer

func helloServiceSayHello(c *bm.Context) {
	p := new(HelloRequest)
	if err := c.BindWith(p, binding.Default(c.Request.Method, c.Request.Header.Get("Content-Type"))); err != nil {
		return
	}
	resp, err := HelloServiceSvc.SayHello(c, p)
	c.JSON(resp, err)
}

// RegisterHelloServiceBMServer Register the blademaster route
func RegisterHelloServiceBMServer(e *bm.Engine, server HelloServiceBMServer) {
	HelloServiceSvc = server
	e.GET("/proto.HelloService/SayHello", helloServiceSayHello)
}
