<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: arith.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 算术运算响应结构
 *
 * Generated from protobuf message <code>proto.ArithResponse</code>
 */
class ArithResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * 乘积
     *
     * Generated from protobuf field <code>int32 pro = 1;</code>
     */
    protected $pro = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $pro
     *           乘积
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Arith::initOnce();
        parent::__construct($data);
    }

    /**
     * 乘积
     *
     * Generated from protobuf field <code>int32 pro = 1;</code>
     * @return int
     */
    public function getPro()
    {
        return $this->pro;
    }

    /**
     * 乘积
     *
     * Generated from protobuf field <code>int32 pro = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPro($var)
    {
        GPBUtil::checkInt32($var);
        $this->pro = $var;

        return $this;
    }

}

